[package]
name = "proximity-rs"
version = "0.1.0"
authors = ["natefduncan <natefduncan@gmail.coM>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools-num = "0.1.3"
